CREATE TABLE IF NOT EXISTS FORNECEDORES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cnpj TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'ATIVO',
  razao_social TEXT NOT NULL,
  nome_fantasia TEXT,
  telefone TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS FORNECEDOR_CONTATOS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fornecedor_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  cargo TEXT,
  telefone TEXT,
  email TEXT,
  FOREIGN KEY (fornecedor_id) REFERENCES FORNECEDORES (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIOS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  cargo TEXT,
  ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GRUPOS_ITENS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL UNIQUE,
  ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ITENS_COMPRA (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo TEXT NOT NULL UNIQUE,
  descricao TEXT NOT NULL,
  unidade TEXT NOT NULL,
  classificacao TEXT NOT NULL DEFAULT 'CUSTO' CHECK (classificacao IN ('CUSTO', 'DESPESA', 'INVESTIMENTO', 'PLR')),
  grupo_id INTEGER NOT NULL,
  controla_estoque INTEGER NOT NULL DEFAULT 0 CHECK (controla_estoque IN (0, 1)),
  ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (grupo_id) REFERENCES GRUPOS_ITENS (id)
);

CREATE TABLE IF NOT EXISTS SOLICITACOES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  solicitante TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ABERTA',
  data_solicitacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SOLICITACAO_ITENS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  solicitacao_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  descricao_necessidade TEXT,
  quantidade REAL NOT NULL,
  FOREIGN KEY (solicitacao_id) REFERENCES SOLICITACOES (id),
  FOREIGN KEY (item_id) REFERENCES ITENS_COMPRA (id)
);
