CREATE TABLE IF NOT EXISTS FORNECEDORES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cnpj TEXT NOT NULL UNIQUE,
  razao_social TEXT NOT NULL,
  nome_fantasia TEXT,
  status TEXT NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS ITENS_COMPRA (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo TEXT NOT NULL UNIQUE,
  descricao TEXT NOT NULL,
  unidade TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SOLICITACOES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  solicitante TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ABERTA',
  data_solicitacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SOLICITACAO_ITENS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  solicitacao_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  descricao_necessidade TEXT,
  quantidade REAL NOT NULL,
  FOREIGN KEY (solicitacao_id) REFERENCES SOLICITACOES (id),
  FOREIGN KEY (item_id) REFERENCES ITENS_COMPRA (id)
);
